### ISSUE TITLE
`HTMLElement is not defined` when using SSR, render function & `createResource`

### ISSUE THREAD

**Issue by johannesspohr** [lxsmnsyc/solid-headless#22]
I don't know if this is actually related to `solid-headless`, or some other weird internals of vite / solid-start, but in this minimal example, variant A causes the server-side rendering to crash, while variant B renders successfully. If I remove the PopoverButton, or use a component with no render function (e.g. `Alert`), there's also no issue.

```
export function Test(): JSX.Element {
    const [ foo ] = createResource(async () => { return "foo"; }); // variant A
    const [ foo ] = createSignal("foo"); // variant B
    return (
        <>
            <div>{foo()}</div>
            <Popover defaultOpen={false}>
                {() => (
                    <>
                        <PopoverButton>
                            <span>Open</span>
                        </PopoverButton>
                    </>
                )}
            </Popover>
    </>
    );
}
```

Stacktrace:
```
An unhandled error occured: ReferenceError: HTMLElement is not defined
    at FocusStartPoint.load (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-headless@0.13.0_solid-js@1.6.5/node_modules/solid-headless/dist/cjs/development/index.cjs:1910:39)
    at Array.<anonymous> (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-headless@0.13.0_solid-js@1.6.5/node_modules/solid-headless/dist/cjs/development/index.cjs:1906:12)
    at cleanNode (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:118:68)
    at Array.<anonymous> (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:387:19)
    at cleanNode (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:118:68)
    at Object.get children [as children] (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:586:20)
    at /Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:187:35
    at /Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:148:49
    at createMemo (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:77:9)
    at children (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:148:16)
    at /Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:187:14
    at createMemo (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:77:9)
    at provider (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:183:12)
    at createComponent (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:283:15)
    at /Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:583:14
    at runWithOwner (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:159:12)
    at runSuspense (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:582:12)
    at Object.completed (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:572:19)
    at notifySuspense (/Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:541:32)
    at /Users/.../sideprojects/solidstarttest/node_modules/.pnpm/solid-js@1.6.5/node_modules/solid-js/dist/server.cjs:484:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by lxsmnsyc** [comment]
yes, this seems to be an issue with solid-headless. Looks like it originates on the focus start point utility.
